### DISCUSSION TITLE
Crowdsec support

### DISCUSSION THREAD

**Discussion by ConGp20** [tobychui/zoraxy#338] [Ideas]
would be nice, if there was a crowdsec parser plugin

**Comment by cowarol** [comment]
that would be nice

**Comment by jyvern** [comment]
+1 🙂

**Comment by heliax01** [comment]
+1 🙂

**Comment by Recentiv** [comment]
+1 🙂

**Comment by king8084** [comment]
pls....

**Comment by barcelona92** [comment]
+1

**Comment by KoenVanduffel** [comment]
Just switched from NPM today. Really impressed!
Crowdsec would definitely make Zoraxy a more complete product.

**Comment by Raithmir** [comment]
I've been testing this for the last couple of days and have log parsing working in Crowdsec.

You'll need to install Crowdsec, the relevant firewall bouncer, and the base HTTP scenarios...
```shell
cscli collections install crowdsecurity/base-http-scenarios
```

Then you'll need to create an acquisition file (/etc/crowdsec/acquis.d/zoraxy.yaml) to point to your log file location...
```
filenames:
  - "/opt/zoraxy/log/zr_*.log"
labels:
  type: "zoraxy"
``` 

Finally create the parser file (/etc/crowdsec/parsers/s01-parse/zoraxy-logs.yaml)...
```
name: raithmir/zoraxy-logs
description: "Parse Zoraxy logs"
filter: "evt.Parsed.program == 'zoraxy'"
onsuccess: next_stage
#debug: true

nodes:
 - grok:
     pattern: '\[%{TIMESTAMP_ISO8601:time_stamp}\] \[router:(?:host-http|whitelist|blacklist|subdomain-http|host-websocket|vdir-http|vdir-websocket|redirect)\] \[origin:%{IPORHOST:target_server}?\] \[client %{IPORHOST:remote_addr}\] %{WORD:verb} %{DATA:request} %{NUMBER:status}'
     apply_on: message
     statics:
       - meta: log_type
         value: http_access-log
       - target: evt.StrTime
         expression: evt.Parsed.time_stamp

statics:
   - meta: service
     value: http
   - meta: source_ip
     expression: evt.Parsed.remote_addr
   - meta: http_status
     expression: evt.Parsed.status
   - meta: http_path
     expression: evt.Parsed.request
   - meta: http_verb
     expression: evt.Parsed.verb
   - meta: target_server
     expression: evt.Parsed.target_server
```


I've submitted a pull request to Crowdsec. Hopefully it will be approved, and you should then be able to just install the collection with the following. This would then install the latest base-http-scenarios and zoraxy-logs parser, leaving you to just set up the acquisition file.

```shell
cscli collections install raithmir/zoraxy-logs
```

**Reply by KoenVanduffel** [reply]
I installed your parser, will report back results when they come in.

**Comment by Raithmir** [comment]
It would be useful if we could get the HTTP user-agent included in the logs, that can be further filtered in the Crowdsec base-http-scenarios. I might have a look at the logging code and submit a pull request if I get chance. I'm not familiar with Go though.

Looks like r.UserAgent() is already captured for the Statistical Analysis view, so presuming it would be easy enough to add to the logs.

**Comment by Raithmir** [comment]
Also, I've not tested this as I'm not running in Docker, but the following may work for the acquisition file if you are (/etc/crowdsec/acquis.d/zoraxy.yaml)...

```
source: docker
container_name:
  - zoraxy
labels:
  type: zoraxy
```

**Reply by LaurenceJJones** [reply]
Yes this will work as long as the logs are written to the container stdout,

**Comment by Raithmir** [comment]
Updated parser file (/etc/crowdsec/parsers/s01-parse/zoraxy-logs.yaml) if you're running the v3.2.0 pre-release (which adds in the useragent in the logs).

```
#
name: raithmir/zoraxy-logs
description: "Parse Zoraxy logs"
filter: "evt.Parsed.program == 'zoraxy'"
onsuccess: next_stage
#debug: true

nodes:
 - grok:
     pattern: '\[%{TIMESTAMP_ISO8601:time_stamp}\] \[router:(?:host-http|whitelist|blacklist|subdomain-http|host-websocket|vdir-http|vdir-websocket|redirect)\] \[origin:%{IPORHOST:target_server}?\] \[client: %{IPORHOST:remote_addr}\] \[useragent: %{DATA:http_user_agent}\] %{WORD:verb} %{DATA:request} %{NUMBER:status}'
     apply_on: message
     statics:
       - meta: log_type
         value: http_access-log
       - target: evt.StrTime
         expression: evt.Parsed.time_stamp

statics:
   - meta: service
     value: http
   - meta: source_ip
     expression: evt.Parsed.remote_addr
   - meta: http_status
     expression: evt.Parsed.status
   - meta: http_path
     expression: evt.Parsed.request
   - meta: http_verb
     expression: evt.Parsed.verb
   - meta: http_user_agent
     expression: "evt.Parsed.http_user_agent"
   - meta: target_server
     expression: evt.Parsed.target_server
```

**Comment by Tschaeeens** [comment]
Hello, thank you very much for the instructions. One question is how to install the crowdsec bouncer. Use zoraxy as Docker on unraid. I also have a crowdsec docker running. I'm just wondering whether I still need the bouncer.

**Comment by Raithmir** [comment]
Updated parser file (/etc/crowdsec/parsers/s01-parse/zoraxy-logs.yaml) to include [router:root-no_resp] log entries where Zoraxy blocks requests for unknown hosts. The pull request to add this to a new Crowdsec hub collection is still awaiting review over there.

```
#
name: raithmir/zoraxy-logs
description: "Parse Zoraxy logs"
filter: "evt.Parsed.program == 'zoraxy'"
onsuccess: next_stage
#debug: true

nodes:
 - grok:
     pattern: '\[%{TIMESTAMP_ISO8601:time_stamp}\] \[router:(?:host-http|whitelist|blacklist|subdomain-http|host-websocket|vdir-http|vdir-websocket|redirect|root-no_resp)\] \[origin:%{IPORHOST:target_server}?\] \[client: %{IPORHOST:>
     apply_on: message
     statics:
       - meta: log_type
         value: http_access-log
       - target: evt.StrTime
         expression: evt.Parsed.time_stamp
statics:
   - meta: service
     value: http
   - meta: source_ip
     expression: evt.Parsed.remote_addr
   - meta: http_status
     expression: evt.Parsed.status
   - meta: http_path
     expression: evt.Parsed.request
   - meta: http_verb
     expression: evt.Parsed.verb
   - meta: http_user_agent
     expression: evt.Parsed.http_user_agent
   - meta: target_server
     expression: evt.Parsed.target_server
```

**Comment by LaurenceJJones** [comment]
Merged @Raithmir collection for Zoraxy please find the collection via https://app.crowdsec.net/hub/author/Raithmir/collections/zoraxy

note parser supports version `3.2.0` and higher only due to useragent being added, let us know and we can probably make the useragent optional until GA

**Comment by Raithmir** [comment]
- Install CrowdSec - https://app.crowdsec.net/security-engines/setup?distribution=linux
- Install relevant firewall bouncer (iptables or nftables) - https://docs.crowdsec.net/u/bouncers/firewall/
- Install Zoraxy collection - `cscli collections install raithmir/zoraxy-logs`

- Create an acquisition file (/etc/crowdsec/acquis.d/zoraxy.yaml) to point to your log file location...
```
filenames:
  - "/opt/zoraxy/log/zr_*.log"
labels:
  type: "zoraxy"
```

Or if you've installed Zoraxy via Docker...
```
source: docker
container_name:
  - zoraxy
labels:
  type: zoraxy
```

- Finally don't forget to enroll the agent in the crowdsec console. You have a command in there when you're logged in similar to...

`sudo cscli console enroll -e context cl8ft6asz11111jmrrrppapye`

**Reply by alien053** [reply]
Hello,

Do you have any information on configuring Crowdsec on Zoraxy, but with Cloudflare in front?
I did what you said, but I can't get any detection from Crowdsec.
Thank you.

**Reply by Raithmir** [reply]
As far as Zoraxy would be concerned, I believe everything would appear to be coming from Cloudflare IP's. Cloudflare's WAF can do much of what Crowdsec would be doing anyway.

**Reply by alien053** [reply]
@Raithmir, Thanks for your feedback. I still think the configuration you're sharing is correct because I had 22 alerts, including one this morning.
I'm just surprised to have significantly fewer alerts than with Traefik. Would Zoraxy be better protected? I'm having trouble understanding why there's such a difference.

**Reply by Raithmir** [reply]
Are you subscribed to any Blocklists in Crowdsec? https://app.crowdsec.net/blocklists/search

**Reply by alien053** [reply]
![image](https://github.com/user-attachments/assets/9b9c4005-40f2-454b-92eb-4c3281b512e6)

Here's what I have.

**Reply by Raithmir** [reply]
Should be good then. Crowdsec will block the IP's in those lists by default and so won't show up as alert detections. Perhaps that's why you're seeing less, I don't know.

**Reply by LaurenceJJones** [reply]
There an issue that not really apparent if you use cloudflare as an upstream proxy it will nullify the firewall remediation so in fact you will currently have no way to enforce decision until zoraxy has some documentation on plugins. (Or you use a cloudflare based remediation) 

(I tried to see if there documentation but got lost reading the current plugins code)

**Reply by tobychui** [reply]
> until zoraxy has some documentation on plugins. 

I am working on it, writing doc is way harder than writing code 😭

**Reply by LaurenceJJones** [reply]
> > until zoraxy has some documentation on plugins. 
> 
> I am working on it, writing doc is way harder than writing code 😭
> 
> 

Believe me I know, I write the crowdsec documention and it takes twice as long than writing code hence why I looked at source code instead.

**Reply by alien053** [reply]
I admit I'm not an expert on reverse proxies and all the associated management, like CloudFlare or anything else. I'm trying to understand what you're saying. If I understand correctly, Crowdsec isn't working properly since I'm using CloudFlare upstream?
Or is there a configuration missing on Zoraxy's end?
Thanks in advance.

**Reply by LaurenceJJones** [reply]
So without getting too complex in short, when you use Cloudflare with "proxy" enabled at layer 3/4 (firewall layer) it only see's the Cloudflare IP address as the proxied IP is at layer 7 (application layer) in the HTTP headers.

So you can use CrowdSec to parse zoraxy logs, but currently you would either need to block on the Cloudflare level with our worker remediation or turn of "proxy" feature of cloudflare. This has to be the case until a plugin can be made for Zoraxy.

This would be exactly the same issue for fail2ban as well as its a network layer thing not an issue with the software.

**Reply by alien053** [reply]
Thanks for the feedback. In that case, how is it that Zoraxy can see the IP address of the user trying to access my website? I can clearly see the IP addresses trying to access my sites from the Zoraxy web interface.
Is this irrelevant? I'm trying to understand.
Thanks.

**Reply by LaurenceJJones** [reply]
> how is it that Zoraxy can see the IP address

That because Zoraxy is on the application layer 7 (http) so it can see the headers sent by Cloudflare.

**Reply by Sph1nX-GER** [reply]
thanks @Raithmir it now works, before it didn't, but thats because my Zoraxy instance was too old. 
I updated to 3.2.4 and now it has the needed UserAgent in the logs and I see the Logs are getting parsed correctly by Crowdsec =)

>cscli parsers inspect Raithmir/zoraxy-logs
type: parsers
stage: s01-parse
name: Raithmir/zoraxy-logs
file_name: zoraxy-logs.yaml
description: Parse Zoraxy logs
path: parsers/s01-parse/Raithmir/zoraxy-logs.yaml
version: "0.1"
dependencies: {}
local_path: /etc/crowdsec/parsers/s01-parse/zoraxy-logs.yaml
local_version: "0.1"
local_hash: xxx
downloadpath: /etc/crowdsec/hub/parsers/s01-parse/Raithmir/zoraxy-logs.yaml
up_to_date: true
tainted: false
belongs_to_collections:
  - Raithmir/zoraxy
installed: true
local: false

Current metrics: 
╭───────────────────────────────────────────────────────────────╮
│ (Parser) Raithmir/zoraxy-logs                                 │
├────────────────────────────────────┬──────┬────────┬──────────┤
│ Parsers                            │ Hits │ Parsed │ Unparsed │
├────────────────────────────────────┼──────┼────────┼──────────┤
│ file:/opt/zoraxy/log/zr_2025-7.log │ 5705 │ 1795   │ 3910     │
╰────────────────────────────────────┴──────┴────────┴──────────╯

**Reply by AnthonyMichaelTDM** [reply]
Shameless plug, but I've been working for the past couple days on creating a dynamic capture plugin to act as a crowdsec bouncer for zoraxy, and it's finally in a working state.
It's very much a work in progress, so I can't guarantee stability, but I'm using it on my server.

Here's a link to the GitHub repo <https://github.com/AnthonyMichaelTDM/zoraxy_crowdsec_bouncer/tree/main>, and see https://github.com/tobychui/zoraxy/discussions/738#discussioncomment-13784037 for a discussion of the current caveats/limitations

**Reply by king8084** [reply]
> Shameless plug, but I've been working for the past couple days on creating a dynamic capture plugin to act as a crowdsec bouncer for zoraxy, and it's finally in a working state. It's very much a work in progress, so I can't guarantee stability, but I'm using it on my server.
> 
> Here's a link to the GitHub repo https://github.com/AnthonyMichaelTDM/zoraxy_crowdsec_bouncer/tree/main, and see [#738 (comment)](https://github.com/tobychui/zoraxy/discussions/738#discussioncomment-13784037) for a discussion of the current caveats/limitations

Is this enough? Or i need to install crowdsrc as well seoerately?

**Reply by EthicalPrivaSecretarium** [reply]
I have the following configured, will work as well, right?

```
filenames:
  - /var/log/zoraxy/*
labels:
  type: zoraxy
  ```

**Reply by EthicalPrivaSecretarium** [reply]
I can see the good thing `level=info msg="Adding file /var/log/zoraxy/zr_2025-10.log to datasources" type=file`

**Comment by EthicalPrivaSecretarium** [comment]
Have installed in TrueNAS so I had to modify the IP and port lines to fit TrueNAS's requirement for dedicated IP 

```
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 80
        target: 80
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 443
        target: 443
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 8000
        target: 8000
    volumes:
      - ./config/:/opt/zoraxy/config/
      - ./plugin/:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FASTGEOIP: "true"
      DOCKER: "true"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: zoraxy-crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/db:/var/lib/crowdsec/data/
      - ./crowdsec/config:/etc/crowdsec/
      - ./config/log:/var/log/zoraxy/:ro
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
networks:
  proxy:
    external: true
```

Using this plugin for Zoraxy: https://github.com/AnthonyMichaelTDM/zoraxy_crowdsec_bouncer/tree/main

All are configured and working properly except when I use cscli decisions add --ip to ban my IP for a test, I can still access to services.

Now I get `[plugin-manager] [system:info] [Crowdsec Bouncer Plugin for Zoraxy:41] time="2025-10-06T21:29:35+02:00" level=warning msg="Signal handler received an error: interrupt error: SIGTERM"`

**Reply by AnthonyMichaelTDM** [reply]
that indicates that something (probably the plugin system) is terminating the plugins process, I see that when I disable the plugin but I assume that's not what's going on?

**Reply by EthicalPrivaSecretarium** [reply]
I always leave the plugin on.

When I use wget command got an 403 forbidden

<img width="524" height="57" alt="image" src="https://github.com/user-attachments/assets/e29bdbf8-8f6a-4db5-be2c-431d5dfa792e" />

**Reply by EthicalPrivaSecretarium** [reply]
<img width="356" height="95" alt="image" src="https://github.com/user-attachments/assets/c370ea12-3177-44ac-a388-af644a84db01" />

They're both OK according to Portainer

**Reply by EthicalPrivaSecretarium** [reply]
<img width="709" height="181" alt="image" src="https://github.com/user-attachments/assets/83051b53-0991-495b-bfca-04a03988300e" />

This works. Still don't know where the issue comes from

**Reply by EthicalPrivaSecretarium** [reply]
Still can access to services after banned it

**Reply by EthicalPrivaSecretarium** [reply]
<img width="858" height="212" alt="image" src="https://github.com/user-attachments/assets/9df899bb-c0d6-4057-8329-37b36c6f1176" />

Is this one of the issue?

**Reply by AnthonyMichaelTDM** [reply]
Oh yeah, you need to create a tag, assign the plugin to that tag, and then tag the services you want protected with the tag.
I should mention that in the readme

**Reply by EthicalPrivaSecretarium** [reply]
How?

Can't wait to read!

**Reply by EthicalPrivaSecretarium** [reply]
<img width="821" height="275" alt="image" src="https://github.com/user-attachments/assets/9f96c5b5-eb9f-4630-b095-d0e8ea6d3a93" />

Okii! There is only "Cloud" on the drop down list.

**Reply by EthicalPrivaSecretarium** [reply]
<img width="1157" height="328" alt="image" src="https://github.com/user-attachments/assets/428f1188-a727-479a-832e-2d47764be8a1" />
Finally seeing some numbers.

Gosh I took 12 hours to troubleshoot. >24 hours ago I begun installing Zoraxy

**Reply by EthicalPrivaSecretarium** [reply]
And now, I could ban myself😌

**Reply by EthicalPrivaSecretarium** [reply]
After I added the collection for Zoraxy, I got banned automatically by some rules that I was accessing my Nextcloud.

Which is so darn good!

Yeah I whitelisted the IP to never ban myself.

**Reply by kabelsalatundklartext** [reply]
> Nachdem ich die Sammlung für Zoraxy hinzugefügt hatte, wurde ich automatisch durch einige Regeln gesperrt, dass ich auf meine Nextcloud zugriff.
> 
> Das ist so verdammt gut!
> 
> Ja, ich habe die IP auf die Whitelist gesetzt, um mich nie selbst zu sperren.

Hello, you mentioned that it took you a bit of time to get it running?

I’m using Unraid myself and have Zoraxy running as a Docker container, but somehow CrowdSec doesn’t communicate with the plugin – and vice versa.

**Reply by zoe-tek** [reply]
Im coming from NPM-plus that is using crowdsec and that is working fine, i tried to follow allong with this and crowdsec does see the zoraxy logs but i ban my internal IP and public IP of my phone and i can still get to everything. Not sure what i'm doing wrong.

**Reply by AnthonyMichaelTDM** [reply]
> Im coming from NPM-plus that is using crowdsec and that is working fine, i tried to follow allong with this and crowdsec does see the zoraxy logs but i ban my internal IP and public IP of my phone and i can still get to everything. Not sure what i'm doing wrong.

Make sure that you give Nextcloud the tag that you have the plugin attached to

**Reply by zoe-tek** [reply]
I have all my proxy hosts set to my homelab label, some one i have the plugin in. I see the plugin showing requests but can not get a block so i feel like missed a config or step.

EDIT: I got it maybeworking, i had the agent IP wrong.  Now i see details in the bouncer list but my phones cell IP still does not get blocked.

Further edit: i got different IPs from sites, api calls thru an app, and a 3rd i saw in the logs. Tried the one in the crowdsec logs and it works.

**Reply by EthicalPrivaSecretarium** [reply]
> Hello, you mentioned that it took you a bit of time to get it running?
> 
> I’m using Unraid myself and have Zoraxy running as a Docker container, but somehow CrowdSec doesn’t communicate with the plugin – and vice versa.

Hoi! 

Sorry for very late reply. It's been tense lately and I even forgot about that.

I did use a custom `compose.yml` code to deploy it on my TrueNAS. `ports` section is indeed modified to be able to set a custom IP to be accepted by TrueNAS.

I learned about by looking at the code while setting a custom IP by deploying an app by using the Web GUI.

First of all both containers should be in the same docker network

```yaml
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 80
        target: 80
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 443
        target: 443
      - host_ip: x.x.x.x
        mode: ingress
        protocol: tcp
        published: 8000
        target: 8000
    volumes:
      - ./config/:/opt/zoraxy/config/
      - ./plugin/:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FASTGEOIP: "true"
      DOCKER: "true"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: zoraxy-crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      #- ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/db:/var/lib/crowdsec/data/
      - ./crowdsec/config:/etc/crowdsec/
      - ./config/log:/var/log/zoraxy/:ro
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
networks:
  proxy:
    external: true
```
