### ISSUE TITLE
[BUG] Headscale does not seem to work with Zoraxy

### ISSUE THREAD

**Issue by lluni** [tobychui/zoraxy#195]
**Describe the bug**
Headscale doesn't work in general and the Headscale-WebUI is not accessible after migrating from a NPM reverse proxy setup to a Zoraxy equivalent setup.

Also, registering devices (tested with Tailscale Android) doesn't work and the Headscale container logs the following warning every ~15s, when using Zoraxy instead of NPM:
`WRN go/src/headscale/hscontrol/noise.go:62 > No Upgrade header in TS2021 request. If headscale is behind a reverse proxy, make sure it is configured to pass WebSockets through.`

This suggests that something is wrong with the WebSocket support and the reverse proxying of vdirs in Zoraxy seems to be different than the reverse proxying of custom locations in NPM (see reproduction step 5-7).

**To Reproduce**
1. Start (a previously in combination with NPM used instance of) Headscale and Headscale-WebUI using the `docker-compose.yml` (see [1])
2. Setup Zoraxy proxy host as shown in the screenshot such that it should be the same as the NPM proxy host (see the other two sceenshots)
3. Try to access `https://headscale.example.com/admin`
4. Nothing happens and the request seems to be proxied to the Headscale
5. Remove the `/` virtual directory and try to access `https://headscale.example.com/admin` again
6. Now, the request seems to be proxied to the WebUI, the browser shows an `Internal Server Error` page and the WebUI container logs an error (see [2]) which suggests that the path wasn't also proxied to it
7. Commenting out the env var `SCRIPT_NAME` in [1] now makes the WebUI reappear as expected under `https://headscale.example.com/admin`

**Expected behavior**
Headscale working as usual and the WebUI being accessible at `https://headscale.example.com/admin`.

**Screenshots**

NPM Headscale proxy host:

![image](https://github.com/tobychui/zoraxy/assets/36239317/60ee9d5f-c0fe-41be-8758-6cda6d1c88cb)

NPM Headscale proxy host custom locations:

![image](https://github.com/tobychui/zoraxy/assets/36239317/e8fb620c-5280-4307-af19-6d4c695b58b3)

Equivalent Zoraxy proxy host:

![image](https://github.com/tobychui/zoraxy/assets/36239317/95d9453d-0ae6-48ec-813a-ee669bb9ea4d)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS:
 - Browser:
 - Version:

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: VPS
 - OS: Ubuntu
 - Version 22.04.4 LTS
 - Docker Version (if you are running Zoraxy in docker): 3.0.6

**Additional context**

[1] Headscale/-WebUI `docker-compose.yml` (`npm_bridge` is used to connect all the different services to NPM and some redacted values and the base domain need to filled in):
```yaml
services:
  headscale:
    image: headscale/headscale:0.22
    container_name: headscale
    restart: unless-stopped
    command: headscale serve
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    networks:
      - npm_bridge
  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
      - COLOR=red                                 # Use the base colors (ie, no darken-3, etc) - 
      - HS_SERVER=https://headscale.example.com   # Reachable endpoint for your Headscale server
      - DOMAIN_NAME=https://headscale.example.com # The base domain name for this container.
      - SCRIPT_NAME=/admin                        # This is your applications base path (wsgi requires the name "SCRIPT_NAME")
      - KEY=REDACTED                              # Generate with "openssl rand -base64 32" - used to encrypt your key on disk.
      - AUTH_TYPE=basic                           # AUTH_TYPE is either Basic or OIDC.  Empty for no authentication
      - LOG_LEVEL=info                            # Log level.  "DEBUG", "ERROR", "WARNING", or "INFO".  Default "INFO"
      # ENV for Basic Auth (Used only if AUTH_TYPE is "Basic").  Can be omitted if you aren't using Basic Auth
      - BASIC_AUTH_USER=REDACTED                  # Used for basic auth
      - BASIC_AUTH_PASS=REDACTED # Used for basic auth
      # ENV for OIDC (Used only if AUTH_TYPE is "OIDC").  Can be omitted if you aren't using OIDC
      #- OIDC_AUTH_URL=https://auth.$DOMAIN/.well-known/openid-configuration # URL for your OIDC issuer's well-known endpoint
      #- OIDC_CLIENT_ID=headscale-webui           # Your OIDC Issuer's Client ID for Headscale-WebUI
      #- OIDC_CLIENT_SECRET=YourSecretHere        # Your OIDC Issuer's Secret Key for Headscale-WebUI
    volumes:
      - ./volume:/data                            # Headscale-WebUI's storage.  Make sure ./volume is readable by UID 1000 (chown 1000:1000 ./volume)
      - ./config/:/etc/headscale/:ro              # Headscale's config storage location.  Used to read your Headscale config.
    networks:
      - npm_bridge

networks:
  npm_bridge:
    external: true
```

[2] Headscale error message:

```
[7] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
    resp, environ = wsgi.create(req, client, addr,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
    path_info = path_info.split(script_name, 1)[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
