### ISSUE TITLE
Network Status Graphs don't render [HELP]

### ISSUE THREAD

**Issue by derwincabral** [tobychui/zoraxy#200]
**What happened?**
More of a visual issue, Network Status doesn't populate the graph. Says "Graph Renderer Paused"
Did an inspect element:  
```
<div id="networkActivityPlaceHolder" style="display: none;">
    <p style="opacity: 0.5;"> Graph Render Paused</p>
</div>
```

**Describe what have you tried**
Not much, This is running in docker with the default compose file as shown below. Went to Network Tools> interface and eth0 is there with 172.19.0.2/16

**Describe the networking setup you are using**
Here are some examples, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? yes 
- Your Zoraxy version? 3.0.6
- Are you using Cloudflare? yes

**Additional context**
All used features work as intended. Tests so far have been pretty great. 

compose.yaml
```
version: "3.3" #can be removed if you are using latest version of docker
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    ports:
      - 80:80
      - 443:443
      - 8000:8000/tcp
    volumes:
      - ./config:/opt/zoraxy/config/
    environment:
      ARGS: -noauth=false
    restart: unless-stopped
networks: {}
```
![image](https://github.com/tobychui/zoraxy/assets/100728215/d49fe801-09bc-4421-82b7-82ea63a5bbf3)
