### ISSUE TITLE
[HELP] Multiple ARGS in docker-compose.yml not working

### ISSUE THREAD

**Issue by Morethanevil** [tobychui/zoraxy#211]
@PassiveLemon 
I tried to use multiple ARGS in docker-compose, but only the first one is used. I wanted to include `-docker=true` until I saw that `-docker=true` is already included in the Dockerfile, but if I want to use for example `-noauth=true`and `-fastgeoip=true` Zoraxy exites immediately.

I tried the way you described in your readme: `Enter them as you would normally.`

```yaml
     environment:
         ARGS: '-noauth=true -fastgeoip=true -webroot=/my/awesome/website'
```

Full example:

```yaml
services:
   zoraxy:
     image: zoraxydocker/zoraxy:latest
     container_name: zoraxy
     restart: unless-stopped
     ports:
       - 80:80
       - 443:443
       - 8005:8000/tcp
     volumes:
       - ./config:/opt/zoraxy/config/
       - /var/run/docker.sock:/var/run/docker.sock
     environment:
       ARGS: '-noauth=true -fastgeoip=true -webroot=/my/awesome/website'
```

Errorlog from console:

```shell
mte@zoraxy/dockertest$ docker compose up
[+] Running 2/2
 ✔ Network apps_default  Created                                                                                                                                                               0.1s 
 ✔ Container zoraxy      Created                                                                                                                                                               0.1s 
Attaching to zoraxy
zoraxy  | invalid boolean value "true -fastgeoip=true -webroot=/my/awesome/website" for -noauth: parse error
zoraxy  | Usage of zoraxy:
zoraxy  |   -autorenew int
zoraxy  |       ACME auto TLS/SSL certificate renew check interval (seconds) (default 86400)
zoraxy  |   -docker
zoraxy  |       Run Zoraxy in docker compatibility mode
zoraxy  |   -fastgeoip
zoraxy  |       Enable high speed geoip lookup, require 1GB extra memory (Not recommend for low end devices)
zoraxy  |   -log
zoraxy  |       Log terminal output to file (default true)
zoraxy  |   -mdns
zoraxy  |       Enable mDNS scanner and transponder (default true)
zoraxy  |   -mdnsname string
zoraxy  |       mDNS name, leave empty to use default (zoraxy_{node-uuid}.local)
zoraxy  |   -noauth
zoraxy  |       Disable authentication for management interface
zoraxy  |   -port string
zoraxy  |       Management web interface listening port (default ":8000")
zoraxy  |   -sshlb
zoraxy  |       Allow loopback web ssh connection (DANGER)
zoraxy  |   -version
zoraxy  |       Show version of this server
zoraxy  |   -webfm
zoraxy  |       Enable web file manager for static web server root folder (default true)
zoraxy  |   -webroot string
zoraxy  |       Static web server root folder. Only allow chnage in start paramters (default "./www")
zoraxy  |   -ztauth string
zoraxy  |       ZeroTier authtoken for the local node
zoraxy  |   -ztport int
zoraxy  |       ZeroTier controller API port (default 9993)
zoraxy exited with code 0
```
Removing the `webroot` or replacing any other parameter does not change this, every time only the first ARG will work.

It would be cool if there is a way to use the parameters as real ENVs like this:

```yaml
     environment:
          noauth: true
          fastgeopip: true
          webroot: '/my/awesome/website'

```
Thanks for your effort!
