### ISSUE TITLE
[HELP] Zoraxy Docker Running Failure

### ISSUE THREAD

**Issue by mbah-dukun** [tobychui/zoraxy#241]
**What happened?**
Zoraxy Docker 3.0.8 running error after upgrade from 3.0.7

**Comment by tobychui** [comment]
Hi @mbah-dukun, thanks for testing out the release so quickly!

I will hand over this issue to our docker maintainer @PassiveLemon

**Comment by PassiveLemon** [comment]
What is the error? Need to know if it's related to Docker or Zoraxy itself

**Comment by mbah-dukun** [comment]
> What is the error? Need to know if it's related to Docker or Zoraxy itself

[_zoraxy-test_logs.txt](https://github.com/user-attachments/files/16232539/_zoraxy-test_logs.txt)

this log from docker

**Comment by PassiveLemon** [comment]
Actually I might know what it is. Could you send either your docker-compose file or docker command for Zoraxy?

**Comment by mbah-dukun** [comment]
> Actually I might know what it is. Could you send either your docker-compose file or docker command for Zoraxy?

`#version: '3.3'
services:
  zoraxy-docker:
    image: zoraxydocker/zoraxy:3.0.7
    container_name: zoraxy
    restart: always
    # privileged: true
    networks:
      vlan-109:
        ipv4_address: 10.100.0.35
#        ipv6_address: 2001:470:eea5::2
    volumes:
      - /home/fajar/zoraxy/config:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MDNS="false"
      - FASTGEOIP="true"
      
  zoraxy-docker-0:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy-test
    privileged: true
    restart: on-failure:5
    volumes:
      - /home/fajar/zoraxy-0/config:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    #environment:
    #  - MDNS=false
    #  - FASTGEOIP=true
    networks:
      vlan-109:
        ipv4_address: 10.100.0.34

networks:
  vlan-109:  
#    enable_ipv6: true
    driver: ipvlan
    driver_opts:
      parent: enp4s0.109
    ipam:
      config:
        - subnet: 10.100.0.32/29
          gateway: 10.100.0.33
#        - subnet: 2001:470:eea5::/126
#          gateway: 2001:470:eea5::1`

this my docker-compose file

**Comment by ojsef39** [comment]
+1, i have the same issue since updating

**Comment by mbah-dukun** [comment]
> > flag provided but not defined: -log
> 
> It seems that is was caused by an extra flag get passed into Zoraxy binary (Sorry I forgot to mention that this is removed due to the apache compatible log format change :P)
> 
> Try to remove the -log flag in the docker file and try again?

yes, its work after rebuild the image

![image](https://github.com/user-attachments/assets/ad3508d7-3a64-420c-8717-4efd55c52096)

```
services:
  zoraxy-docker:
    image: zoraxydocker/zoraxy:3.0.7
    container_name: zoraxy
    restart: always
    networks:
      vlan-109:
        ipv4_address: 10.100.0.35
    volumes:
      - /home/fajar/zoraxy/config:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MDNS=false
      - FASTGEOIP=true
      
  zoraxy-docker-0:
    image: zoraxy:test
    container_name: zoraxy-test
    privileged: true
    restart: on-failure:5
    volumes:
      - /home/fajar/zoraxy-0/config:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      vlan-109:
        ipv4_address: 10.100.0.34

networks:
  vlan-109:
    driver: ipvlan
    driver_opts:
      parent: enp4s0.109
    ipam:
      config:
        - subnet: 10.100.0.32/29
          gateway: 10.100.0.33
```
[_zoraxy-test_logs (2).txt](https://github.com/user-attachments/files/16233349/_zoraxy-test_logs.2.txt)
