### ISSUE TITLE
[Possible BUG] using "PORT" enviroment lead to unresponsive GUI and "time out" requests to the proxy

### ISSUE THREAD

**Issue by NeoMod** [tobychui/zoraxy#260]
**What happened?**

I have been using Zoraxy for a while under docker, with a simple compose file and the latest tag on Portainer Business 2.20.3

```
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    networks:
       neobridge:
           ipv4_address: 172.18.0.8
    ports:
      - 80:80
      - 443:443
      - 8081:8000/tcp
    volumes:
      - /mnt/user/dockerdata/zoraxy_data/:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime #added from latest example
    environment:
      - ARGS=-noauth=false
      #- PORT=8081 #commented out after issue discovery, working good so far.
      - FASTGEOIP=true
    labels:
      - "net.unraid.docker.icon=/mnt/user/dockerdata/icons/zoraxy.png"
          
networks:
  neobridge:
    external: true
```

Recently I noticed I had what appeared to be an issue with my reverse proxies: they were pointing to the default webpage instead of the respective services.

I did a bit of research and found out about this [comment](https://github.com/tobychui/zoraxy/issues/245#issuecomment-2230165146)  and after a quick inspection I discovered all the _.config_ files were missing the `OriginIpOrDomain` value.

I recovered the previous backup and restarted the container. However, I noticed another issue: the admin interface wasn’t available; all proxies were working as expected but I couldn’t reach the admin interface on my custom port (_8081_).

While checking for other changes, I noticed the presence of this “warning” inside the [docker folder](https://github.com/tobychui/zoraxy/tree/main/docker).

![image](https://github.com/user-attachments/assets/c1371a62-cefa-4bf5-89c0-1e4ab4caaa84)

**Describe what have you tried**

I then changed the compose file to reflect this “_new but also not-new_” change (as PassiveLemon kindly noted in #259) and for a while the situation seemed resolved. Although I could notice other issues sporadically appearing while using other services behind reverse proxy, (_mainly “timed out” requests resulting in abnormal request termination_), I didn’t notice immediately but after a while that the admin interface was again not available.

Seeing the “PORT” option is mentioned in the description but not in the docker file provided, I tried starting Zoraxy without it and it worked.
So far it’s working correctly, the admin menu is available without issues, and staying responsive on custom port for admin interface.
Now, the question would be…is this a bug or a simple misunderstanding about some documentation in need of an update? 

**Describe the networking setup you are using**

- Are you using the docker build of Zoraxy? [yes, Docker version 24.0.9, build 2936816; ports forwarded directly to the container]
- Your Zoraxy version? [e.g. 3.0.9]
- Are you using Cloudflare? [yes]
- Are your system hosted under a NAT router? [yes, docker server under 192.168.0.0/24 with some internally configured "bridge" networks under 172.18.0.x for containers. Operating under UNRAID so configs are a bit different than usual, but not the first time using a reverse proxy. Migradet from NGM at the beginning, no issues so far.]
