### ISSUE TITLE
[ENHANCEMENTS] Include forward authentication support

### ISSUE THREAD

**Issue by alceasan** [tobychui/zoraxy#33]
**Is your feature request related to a problem? Please describe.**
Forward authentication to external platforms, like Keycloak, Authentik or Authelia. This is necessary to provide SSO and protect services that doesn't have its own authentication services (or very insecure ones, like Basic Auth).

**Describe the solution you'd like**
To be able to configure forward auth in the web UI.

**Additional context**
Examples for other reverse proxy platforms:
[Authelia](https://www.authelia.com/integration/proxies/introduction)
[Authentik](https://goauthentik.io/docs/providers/proxy/forward_auth)

**Comment by lephtHanded** [comment]
I agree with @bleomycin - integration with authelia/authentik is the only thing holding me back.

**Comment by tobychui** [comment]
@ciotorcristian 
Nope, seems no one is working on this nor I need this feature myself. As always, PRs are welcomed 👍🏻

**Comment by gagnfra** [comment]
I'm adding my voice to this request. The only thing that hold me back to use it.

**Comment by asraelvudogel** [comment]
+1

**Comment by ph0b0s101** [comment]
Yeah this feature is the only one missing, which holds me back so far ;-)

**Comment by CrazyWolf13** [comment]
that's really the only feature that is stopping me from using this, tbh. the rest looks amazing!

**Comment by swoop124** [comment]
+1
i'am also interested in this feature

**Comment by XHyperDEVX** [comment]
right here +1

that's the only thing keeping me from switching from NPM to Zoraxy right now.

There is still no update for this? Are people working on it? @tobychui?

**Comment by tobychui** [comment]
@XHyperDEVX No, as far as I know no one pickup on this yet. As this is an open source project, you wanna try contribute some code and open a PR?

**Comment by XHyperDEVX** [comment]
okay, too bad.

i would do it immediately! i see here how many people i could help with it (and for how many this is the reason why they haven't switched to zoraxy yet), but unfortunately i don't understand “go”, my home is c#.

if i could i would implement this feature immediately, but unfortunately i can't..
is there anyone else here who would be able to do this?

**Comment by bentschrader** [comment]
+1 
Would be the perfect replacement for NPM.

**Comment by djcroman** [comment]
Any News here?

**Comment by XHyperDEVX** [comment]
@djcroman unfortunately no... if you can contribute we would all be very grateful

**Comment by 7brend7** [comment]
Though basic auth is not working for me (`handleBasicAuth`), I managed to integrate `authelia` into `zoraxy`. However, it’s not a forward auth setup. Instead, it uses a simple `verify` request with an `authelia` session cookie as a replacement for basic authentication.
```
package dynamicproxy

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
)

func (h *ProxyHandler) handleAutheliaAuthRouting(w http.ResponseWriter, r *http.Request, pe *ProxyEndpoint) error {
	err := handleAutheliaAuth(w, r, pe)
	if err != nil {
		h.Parent.logRequest(r, false, 401, "host", r.URL.Hostname())
	}
	return err
}

func handleAutheliaAuth(w http.ResponseWriter, r *http.Request, pe *ProxyEndpoint) error {

	client := &http.Client{}

	req, err := http.NewRequest("POST", "https://authelia.mydomain.com/api/verify", nil)
	if err != nil {
		pe.parent.Option.Logger.PrintAndLog("Authelia", "Unable to create request", err)
		w.WriteHeader(401)
		return errors.New("unauthorized")
	}

	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	req.Header.Add("X-Original-URL", fmt.Sprintf("%s://%s", scheme, r.Host))

	// Copy cookies from the incoming request
	for _, cookie := range r.Cookies() {
		req.AddCookie(cookie)
	}

	resp, err := client.Do(req)
	if err != nil {
		pe.parent.Option.Logger.PrintAndLog("Authelia", "Unable to verify", err)
		w.WriteHeader(401)
		return errors.New("unauthorized")
	}

	if resp.StatusCode != 200 {
		redirectURL := "https://authelia.mydomain.com/?rd=" + url.QueryEscape(scheme+"://"+r.Host+r.URL.String()) + "&rm=" + r.Method

		http.Redirect(w, r, redirectURL, http.StatusSeeOther)
		return errors.New("unauthorized")
	}

	return nil
}
```
It’s quite simple: every request proxied by `zoraxy` is checked for host verification in `authelia`. If the verification fails, the user is redirected to `authelia`, where a cookie token is set after login. This cookie is domain-specific, so it’s crucial that both `authelia` and the target application are under the same domain level. Once the cookie is set, the verification process should pass.
I’m not sure if it’s a good approach or if it might overload my network traffic, affect performance, or increase latency.

---------------

here i a local demo (but it also works in real domain):

docker-compose.yml:
```
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    ports:
      - 9091:9091
    volumes:
      - '${PWD}/data/authelia/config:/config'

  zoraxy-docker:
    image: zoraxydocker/zoraxy:latest
    restart: 'unless-stopped'
    container_name: zoraxy
    extra_hosts:
      - "authelia.mydomain.com:172.17.0.1"
    ports:
      - 80:80
      - 443:443
      - 81:8000/tcp
    volumes:
      - ./zoraxy_config:/opt/zoraxy/config/

  http-server:
    image: hashicorp/http-echo
    ports:
      - 82:5678
```

configuration.yml:
```
access_control:
  default_policy: 'deny'
  rules:
    - domain:
        - "authelia.mydomain.com"
      policy: bypass
    - domain:
        - "*.mydomain.com"
      policy: one_factor
authentication_backend:
  file:
    path: '/config/users_database.yml'
session:
  cookies:
    -
      name: 'authelia_session'
      domain: 'mydomain.com'
      authelia_url: 'https://authelia.mydomain.com'
      inactivity: '5 minutes'
      expiration: '2 hours'
      remember_me: '1 month'
storage:
  encryption_key: '12345678901234567890'
  local:
    path: '/config/db.sqlite3'
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
identity_validation:
  reset_password:
    jwt_secret: '123'
server:
  address: 'tcp://:9091/'
```

hosts:
```
127.0.0.1 	test.mydomain.com zoraxy.mydomain.com authelia.mydomain.com
```

https://github.com/user-attachments/assets/ba806a29-22fe-4be2-8e5d-937bf5e384f1
