### ISSUE TITLE
[HELP] nil pointer dereference when running on docker swarm stack

### ISSUE THREAD

**Issue by AqujZ1K9** [tobychui/zoraxy#394]
I am attempting to deploy Zoraxy in a Docker Swarm stack. While the first container (with a scale of 3) starts without any issues, any additional containers fail with the following error trace:

```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
CA certificates updated
ZeroTier daemon started
Starting Zoraxy...
Checking required config update
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x25e1ef3]
goroutine 11 [running]:
imuslab.com/zoraxy/mod/netstat.(*NetStatBuffers).Close(0x0)
/opt/zoraxy/source/mod/netstat/netstat.go:172 +0x13
main.ShutdownSeq()
/opt/zoraxy/source/main.go:125 +0xa5
main.SetupCloseHandler.func1()
/opt/zoraxy/source/main.go:115 +0x1e
created by main.SetupCloseHandler in goroutine 1
/opt/zoraxy/source/main.go:113 +0xb6
```

my compose file:

```
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8005:8000
    deploy:
      replicas: 3
    volumes:
      - /mnt/dockerswarmstorage01/zoraxy/zoraxy/config/:/opt/zoraxy/config/
      - /mnt/dockerswarmstorage01/zoraxy/zerotier/config/:/var/lib/zerotier-one/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    environment:
      FASTGEOIP: "true"
      ZEROTIER: "true"
```

Has anyone successfully deployed Zoraxy in a Docker Swarm or Kubernetes stack?
