### ISSUE TITLE
[ENHANCEMENTS] Set DNS for Zoraxy?

### ISSUE THREAD

**Issue by krosseyed** [tobychui/zoraxy#453]
**Is your feature request related to a problem? Please describe.**
I have a need to point Zoraxy's DNS server to something that is not 172.17.0.2

**Describe the solution you'd like**
An webui option under settings or a docker environment variable that allows you to modify the DNS server that Zoraxy is looking at for DNS requests

**Describe alternatives you've considered**
I currently have to run `echo "nameserver <IP_ADDRESS_OF_DNS>" > /etc/resolve.conf` from within the docker container to fix this.

**Additional context**
I am pretty sure this is useful to others, as being able to reverse proxy over the internet will need to have both working HTTPS and DNS to function.

**Comment by PassiveLemon** [comment]
have you tried using the Docker option for DNS? For example:
```
services:
  zoraxy:
    image: zoraxydocker/zoraxy:3.1.6
    container_name: zoraxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/Containers/Test/Zoraxy-e/config/:/opt/zoraxy/config/:rw
    environment:
      FASTGEOIP: "true"
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8000:8000/tcp
    dns:
      - (IP of DNS container)
```
