### ISSUE TITLE
[HELP] Invalid SSL Certificate (526) Error with Cloudflare Full (Strict) and Zoraxy

### ISSUE THREAD

**Issue by spikeganush** [tobychui/zoraxy#576]
<html><head></head><body><h1>Invalid SSL Certificate (526) Error with Cloudflare Full (Strict) and Zoraxy</h1>

## Environment Details

| Component | Version/Details |
|-----------|----------------|
| Zoraxy Version | 3.1.9 |
| Docker Host OS | Ubuntu 22.04 |
| Domain Registrar | Cloudflare |
| Cloudflare SSL Setting | Full (Strict) |
| Cloudflare Origin Certificate | Downloaded 15-year certificate |
| NAT Router | port 80 - 443 - 8200 forwarded to the Zoraxy Docker local IP |
## Infrastructure Setup

My setup consists of:
1. Homelab server running Proxmox
2. Proxmox container named "proxy" running Ubuntu 22.04
3. Docker and Portainer installed on the proxy container
4. Zoraxy running in Docker with the configuration below 

## Docker Compose Configuration

```yaml
services:
  zoraxy-docker:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    ports:
      - 80:80
      - 443:443
      - 8200:8200
    volumes:
      - ./config:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    environment:
      PORT: "8200" 
  ddns:
    image: 'favonia/cloudflare-ddns:latest'
    container_name: cloudflare-ddns
    # network_mode: host # This bypasses network isolation and makes IPv6 easier (optional; see below)
    restart: unless-stopped
    user: "1000:1000" # Run the updater with specific user and group IDs (in that order).
    read_only: true # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all] # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true] # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - CLOUDFLARE_API_TOKEN=[REDACTED]
      - DOMAINS=fakeDomain.vip
      - PROXIED=true
      - IP6_PROVIDER=none
# For testing the proxy
  helloworld:
    image: 'karthequian/helloworld:latest'
    container_name: helloworld
    restart: unless-stopped
    ports:
      - 8888:80/tcp      
```

## Cloudflare Configuration

- Domain pointing to my public IP address
- CNAME wildcard pointing to the root domain
- SSL set to Full (Strict)
- Downloaded 15-year Origin Certificate from Cloudflare
- Installed the Cloudflare Origin Certificate as fallback SSL key in Zoraxy

## Zoraxy Configuration

- TLS is enabled in Zoraxy
- Using Cloudflare Origin Certificate as fallback SSL key

## Issue Description

When creating a new proxy in Zoraxy and attempting to access it through my domain, I receive a Cloudflare 526 error (Invalid SSL certificate).

I have verified that I can access the server normally when:
- SSL is turned OFF in Cloudflare
- TLS is turned OFF in Zoraxy

This suggests the issue is specifically with the SSL/TLS configuration between Cloudflare and Zoraxy.

I've followed the advice in [[this similar issue](https://github.com/tobychui/zoraxy/issues/301)](https://github.com/tobychui/zoraxy/issues/301), but I'm still experiencing the problem.

## Troubleshooting Steps Already Performed

1. Verified that the Cloudflare Origin Certificate is correctly installed in Zoraxy
2. Confirmed that the domain DNS records are correctly set up in Cloudflare
3. Tested with SSL/TLS disabled on both ends (works correctly)
4. Ensured Zoraxy container has proper port mappings for HTTP/HTTPS
5. Zoraxy used port 8200, port forwarded to the NAT router, accessible with the public IP.

## Question

Is there anything specific about the interaction between Cloudflare's Full (Strict) mode and Zoraxy's TLS implementation that I'm missing? Any additional configuration needed to make this work correctly?

## Screenshots
The domain was modified in Dev tools for this post.

![Image](https://github.com/user-attachments/assets/9402130a-0bd4-40dd-86fb-99362a9e36bd)
![Image](https://github.com/user-attachments/assets/14ad0452-75a3-453e-9258-a932390c4450)
![Image](https://github.com/user-attachments/assets/51bba833-3c79-4402-9347-4e8aa0372cae)
![Image](https://github.com/user-attachments/assets/305675ef-2a32-4ade-a21d-8a472861c706)
