### ISSUE TITLE
[HELP] Endless Auth Process

### ISSUE THREAD

**Issue by Lvshujun0918** [tobychui/zoraxy#634]
**Setting**
**Note: I use the real uri below, All port is 5208 for I set Zoraxy's HTTPS port on that.**
I set up Authelia, and using Zoraxy to proxy it to "https://auth.home.cszj.wang:5208" (not a standard port).
Then I set another host ("https://home.cszj.wang:5208") in "Authelia" mode and set as follow.
![Image](https://github.com/user-attachments/assets/60c72aa1-c564-4901-873f-5d6a0ccfd877)
![Image](https://github.com/user-attachments/assets/323adaed-38af-4ca5-ad8b-2adcfc8bfeb5)
**Authelia Config**
```yaml
access_control:
  default_policy: 'deny'
  rules:
    - domain:
        - "auth.home.cszj.wang"
      policy: bypass
    - domain:
        - "*.home.cszj.wang"
      policy: one_factor
authentication_backend:
  file:
    path: '/config/users_database.yml'
  password_reset:
    disable: true
session:
  cookies:
    -
      name: 'authelia_session'
      domain: 'home.cszj.wang'
      authelia_url: 'https://auth.home.cszj.wang:5208'
      inactivity: '5 minutes'
      expiration: '2 hours'
      remember_me: '1 month'
storage:
  encryption_key: '...'
  local:
    path: '/config/db.sqlite3'
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
identity_validation:
  reset_password:
    jwt_secret:  '...'
server:
  address: 'tcp://:9091/'
```
**What happened?**
When I visit "https://home.cszj.wang:5208", I was redirected to "https://auth.home.cszj.wang:5208/?rd=https%3A%2F%2Fhome.cszj.wang%3A5208%2F&rm=GET", that's right.

But after I typing the right user name and password, the page can't direct back to "https://home.cszj.wang:5208", it instead get into endless redirection.

By mannual visiting "https://auth.home.cszj.wang:5208", I can see below, showing that I have logined in successfully, but for some reason I can't jump out of the Auth circle. Could anyone help?
![Image](https://github.com/user-attachments/assets/3310816f-b1c1-4445-8d24-b6ce34fb4b71)
**Docker Setting**
```yaml
services:
  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia:latest'
    restart: 'unless-stopped'
    ports:
      - 9091:9091
    volumes:
      - '**:/config'
    environment:
      TZ: 'Asia/Shanghai'
  zoraxy-docker:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    network_mode: host
    volumes:
      - ***:/opt/zoraxy/config/
    environment:
      ARGS: '-noauth=false'
      PORT: 9000
      SSHLB: true
      TZ: 'Asia/Shanghai'
```
**Describe the networking setup you are using**
Here are some example, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? yes
- Your Zoraxy version? v3.2.0
- Are you using Cloudflare? no
- Are your system hosted under a NAT router? no
